export enum Action {
  OPEN_SNACKBAR = 'OPEN_SNACKBAR',
  CLOSE_SNACKBAR = 'CLOSE_SNACKBAR',
  CHANGE_WALLET_DATE = 'CHANGE_WALLET_DATE',
  OPEN_CATEGORY_DIALOG = 'CATEGORY_DIALOG',
  CLOSE_CATEGORY_DIALOG = 'CLOSE_CATEGORY_DIALOG',
  DIALOG_DELETION_OPEN = 'DIALOG_DELETION_OPEN',
  DIALOG_DELETION_CLOSE = 'DIALOG_DELETION_CLOSE'
}
